# K8s Manus - k3s Specific Configuration
# ======================================

global:
  namespace: k8s-manus
  domain: wazzan.us
  hostIP: 10.10.10.131
  storageClass: local-path  # k3s default storage class

# Authentication credentials
auth:
  adminUser: alwazw
  adminPassword: WaficWazzan!2
  adminEmail: wafic@wazzan.us

# Database configurations
databases:
  postgres:
    enabled: true
    image:
      repository: postgres
      tag: "15-alpine"
    database: authentik
    username: authentik
    password: WaficWazzan!2
    port: 5432
    storage: 5Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  mysql:
    enabled: true
    image:
      repository: mysql
      tag: "8.0"
    rootPassword: WaficWazzan!2
    database: grafana
    username: grafana
    password: WaficWazzan!2
    port: 3306
    storage: 5Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  redis:
    enabled: true
    image:
      repository: redis
      tag: "7-alpine"
    password: WaficWazzan!2
    port: 6379
    storage: 2Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# Authentik SSO
authentik:
  enabled: true
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2024.2.2"
  secretKey: "this-is-a-very-secure-secret-key-change-in-production"
  port: 9000
  subdomain: authentik
  replicas: 1
  worker:
    enabled: true
    replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Grafana
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "latest"
  port: 3000
  subdomain: grafana
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# PgAdmin
pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: "latest"
  port: 5050
  subdomain: pgadmin
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Dashboard services
dashboards:
  heimdall:
    enabled: true
    image:
      repository: lscr.io/linuxserver/heimdall
      tag: "latest"
    port: 8080
    subdomain: heimdall
    replicas: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  homer:
    enabled: true
    image:
      repository: b4bz/homer
      tag: "latest"
    port: 8081
    subdomain: homer
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

# Networking configuration
networking:
  # NodePort for direct access (recommended for k3s)
  nodePort:
    enabled: true
    ports:
      authentik: 30900
      grafana: 30300
      pgadmin: 30505
      heimdall: 30808
      homer: 30801

  # Ingress with Traefik (k3s default)
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    tls:
      enabled: false  # Disable TLS for initial testing

# Storage configuration
storage:
  persistentVolumes:
    enabled: true
    storageClass: local-path  # k3s default
    accessMode: ReadWriteOnce

# Security configuration
security:
  rbac:
    enabled: true
  networkPolicies:
    enabled: false  # Disable for initial testing
  podSecurityStandards:
    enabled: false  # Disable for initial testing

# Resource management
resources:
  # Global resource limits
  defaultRequests:
    memory: "128Mi"
    cpu: "100m"
  defaultLimits:
    memory: "512Mi"
    cpu: "500m"

