apiVersion: v2
name: k8s-manus
description: A comprehensive Kubernetes stack with SSO authentication, monitoring, and database management services
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/alwazw/k8s_manus
sources:
  - https://github.com/alwazw/k8s_manus
maintainers:
  - name: alwazw
    email: wafic@wazzan.us
keywords:
  - kubernetes
  - sso
  - authentik
  - grafana
  - monitoring
  - dashboard
  - postgresql
  - mysql
  - redis
annotations:
  category: Infrastructure
dependencies: []

