# K8s Manus Stack - Helm Values Configuration
# Production-ready Kubernetes deployment with SSO integration

# Global Configuration
global:
  namespace: k8s-manus
  domain: wazzan.us
  hostIP: 10.10.10.131
  storageClass: standard
  
# Image Configuration
images:
  postgres:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  mysql:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  authentik:
    repository: ghcr.io/goauthentik/server
    tag: "2024.12.1"
    pullPolicy: IfNotPresent
  grafana:
    repository: grafana/grafana
    tag: "latest"
    pullPolicy: IfNotPresent
  pgadmin:
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent
  heimdall:
    repository: lscr.io/linuxserver/heimdall
    tag: "latest"
    pullPolicy: IfNotPresent
  homer:
    repository: b4bz/homer
    tag: "latest"
    pullPolicy: IfNotPresent

# Authentication & Credentials
auth:
  adminUser: alwazw
  adminPassword: WaficWazzan!2
  adminEmail: wafic@wazzan.us
  
# Database Configuration
databases:
  postgres:
    enabled: true
    database: authentik
    username: authentik
    password: WaficWazzan!2
    port: 5432
    storage: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
        
  mysql:
    enabled: true
    rootPassword: WaficWazzan!2
    database: grafana
    username: grafana
    password: WaficWazzan!2
    port: 3306
    storage: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
        
  redis:
    enabled: true
    password: WaficWazzan!2
    port: 6379
    storage: 5Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# Authentik SSO Configuration
authentik:
  enabled: true
  secretKey: this-is-a-very-secure-secret-key-for-authentik-development-please-change-in-production
  port: 9000
  subdomain: authentik
  replicas: 1
  worker:
    replicas: 1
  resources:
    server:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    worker:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

# Grafana Configuration
grafana:
  enabled: true
  port: 3000
  subdomain: grafana
  replicas: 1
  plugins:
    - grafana-clock-panel
    - grafana-simple-json-datasource
  oauth:
    enabled: true
    clientId: grafana
    clientSecret: grafana-secret
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# PgAdmin Configuration
pgadmin:
  enabled: true
  port: 5050
  subdomain: pgadmin
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Dashboard Services
dashboards:
  heimdall:
    enabled: true
    port: 8080
    subdomain: heimdall
    replicas: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
        
  homer:
    enabled: true
    port: 8081
    subdomain: homer
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "50m"

# Networking Configuration
networking:
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    tls:
      enabled: false
      secretName: k8s-manus-tls
      
  nodePort:
    enabled: true
    
  loadBalancer:
    enabled: false

# Storage Configuration
storage:
  persistentVolumes:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    
# Security Configuration
security:
  networkPolicies:
    enabled: true
  podSecurityStandards:
    enabled: true
  rbac:
    enabled: true
    
# Monitoring Configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false

# Backup Configuration
backup:
  enabled: false
  schedule: "0 2 * * *"
  retention: 7

