---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: k8s-manus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: {{ .Values.databases.postgres.password | b64enc }}
  postgres-username: {{ .Values.databases.postgres.username | b64enc }}
  postgres-database: {{ .Values.databases.postgres.database | b64enc }}
  mysql-root-password: {{ .Values.databases.mysql.rootPassword | b64enc }}
  mysql-password: {{ .Values.databases.mysql.password | b64enc }}
  mysql-username: {{ .Values.databases.mysql.username | b64enc }}
  mysql-database: {{ .Values.databases.mysql.database | b64enc }}
  redis-password: {{ .Values.databases.redis.password | b64enc }}

---
# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: k8s-manus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: application
type: Opaque
data:
  admin-username: {{ .Values.auth.adminUser | b64enc }}
  admin-password: {{ .Values.auth.adminPassword | b64enc }}
  admin-email: {{ .Values.auth.adminEmail | b64enc }}

---
# Authentik Secrets
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: authentication
type: Opaque
data:
  secret-key: {{ .Values.authentik.secretKey | b64enc }}

---
# Grafana OAuth Secrets
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: application
type: Opaque
data:
  client-id: {{ .Values.grafana.oauth.clientId | b64enc }}
  client-secret: {{ .Values.grafana.oauth.clientSecret | b64enc }}

